# Generated by Django 5.2.5 on 2025-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('bird_species', models.CharField(max_length=120)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='frames/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
